#server:
#   port: 8761
#
#eureka:
#   instance:
#       hostname: localhost
#   client:
#       registerWithEureka: true
#       fetchRegistry: false
#       serviceUrl:
#           defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8762
spring:
    application:
        name: service-helloworld

